### ISSUE TITLE
A good tip for beginners ;) / if bluetooth got some crazy behaviour

### ISSUE THREAD

**Issue by DaMusikant** [JasonLG1979/PiZero-Bluetooth-Audio-Receiver#1]
Hi there,
this is not a issue, not anymore. 
I had problems for hours that the bluetooth was not working correctly and the symptoms were not clear.
But dissabling the wifi solved everything within minutes. It seems that the Zero got some serious problems getting both to work.
Your code is excellent, works great now, thank you :)

This is just a simple tip, I didn't knew were to put that so I placed it here. You can remove it or tell me where's a better place if there's one.

**Comment by JasonLG1979** [comment]
I have heard that other's have had troubles with bluetooth with wifi enabled that's why I included this:
https://github.com/JasonLG1979/PiZero-Bluetooth-Audio-Receiver#limitations
