### ISSUE TITLE
Couldn't pair with raspberrypi0 because of an incorrect PIN or passkey.

### ISSUE THREAD

**Issue by pvanthony** [JasonLG1979/PiZero-Bluetooth-Audio-Receiver#2]
Hi,
Currently getting the following error.
"Couldn't pair with raspberrypi0 because of an incorrect PIN or passkey."

Please note it was working fine at the start. I disconnected my android phone and also set to forget the bluetooth.
Then connected with windows 10 and it worked fine.
Disconnected from windows 10 and set to forget the bluetooth.

Then tried to connect again and got the following error.
"Couldn't pair with raspberrypi0 because of an incorrect PIN or passkey."

Next added the following lines to the bottom of /boot/config.txt
force_turbo=1
dtoverlay=disable-wifi

That did not help also.

Any idea how to solve this issue?

P.V.Anthony

**Comment by pvanthony** [comment]
Found the following solution here.
https://www.raspberrypi.org/forums/viewtopic.php?t=304434

So after the raspberry pi zero w has booted up, then ssh in and run the following command,
/usr/bin/bt-agent --capability=DisplayOnly -p /home/pi/pins

And it works!

Any idea how to integrate this so that it will work when the raspberry boots up?

**Comment by JasonLG1979** [comment]
> Any idea how to integrate this so that it will work when the raspberry boots up?

Sure, just change the args in the service (`bt-agent.service`).

**Comment by pvanthony** [comment]
Just tried changing the args but the service fails. Here is the status.
```$ sudo systemctl status bt-agent
● bt-agent.service - Bluetooth Agent
   Loaded: loaded (/etc/systemd/system/bt-agent.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-08-05 16:05:30 BST; 4min 16s ago
  Process: 404 ExecStart=/usr/bin/bt-agent --capability=DisplayOnly -p /home/pi/pins (code=exited, status=1/FAILURE)
 Main PID: 404 (code=exited, status=1/FAILURE)

Aug 05 16:05:30 raspberrypi0 systemd[1]: bt-agent.service: Service RestartSec=100ms expired, scheduling restart.
Aug 05 16:05:30 raspberrypi0 systemd[1]: bt-agent.service: Scheduled restart job, restart counter is at 5.
Aug 05 16:05:30 raspberrypi0 systemd[1]: Stopped Bluetooth Agent.
Aug 05 16:05:30 raspberrypi0 systemd[1]: bt-agent.service: Start request repeated too quickly.
Aug 05 16:05:30 raspberrypi0 systemd[1]: bt-agent.service: Failed with result 'exit-code'.
Aug 05 16:05:30 raspberrypi0 systemd[1]: Failed to start Bluetooth Agent.
```
Changed the args back to  /usr/bin/bt-agent --capability=NoInputNoOutput and the service starts good

Anything else that can be tried?

**Comment by pvanthony** [comment]
Finally got it to work. 
Thank you for the advice. 
The issue I think was the pins file permission.

Here is what was done.

Create a file called "pins" and save it at /usr/local/etc/
In the file have the following.
`* *`

Change ownership of the "pins" file.
chown bt-agent:bt-agent pins

Change permission of the "pins" file.
chmod 640 pins

Then change the args of the bt-agent.service file to the following.
ExecStart=/usr/bin/bt-agent --capability=DisplayOnly --pin /usr/local/etc/pins

Then do this command.
sudo systemctl daemon-reload

That should do it.

Enjoy!

Hope the file locations and settings are ok. Please advice.

**Comment by JasonLG1979** [comment]
> The issue I think was the pins file permission.

Alternatively you could change the user who the service is run under. The bluetooth agent service runs under the unprivileged `bt-agent` user. If the service ran as root (many systemd services do) it would not matter where the file was nor the file permissions. You could also use `pi` as the user.

**Comment by pvanthony** [comment]
Thank you very much for the advice.
