### ISSUE TITLE
Error in bluealsa-aplay unit file

### ISSUE THREAD

**Issue by MrBuddyCasino** [JasonLG1979/PiZero-Bluetooth-Audio-Receiver#3]
In my tests `bluealsa-aplay` was unable to find the soundcard with the `PrivateDevices=true` enabled:

"That line hides all devices from the bluealsa-aplay process, including all sound cards." => see https://githubmemory.com/repo/Arkq/bluez-alsa/issues/324

Removing that line fixed it.

**Comment by JasonLG1979** [comment]
`bluealsa-aplay` doesn't contain `PrivateDevices=true`.

The `bluealsa-aplay.service` file in the [`README.md`](https://github.com/JasonLG1979/PiZero-Bluetooth-Audio-Receiver#readme) in this repo reads:

```
[Unit]
Description=Bluealsa audio player
Requires=bluealsa.service
After=bluealsa.service

[Service]
Type=simple
ExecStart=/usr/bin/bluealsa-aplay --profile-a2dp --single-audio 00:00:00:00:00:00
Restart=on-failure
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
RemoveIPC=true
RestrictAddressFamilies=AF_UNIX
User=bluealsa
Group=audio
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
```

**Comment by MrBuddyCasino** [comment]
Oh I'm sorry, not sure how that got in there. Maybe I accidentally copied it from `bluealsa.service`.
